name:                chopping-benchmark
version:             0.1.0.0

dependencies:
- base >= 4.7 && < 5
- random
- criterion

benchmarks:
  chopping-benchmark-bench:
    main: Bench.hs
    source-dirs: bench
    ghc-options:
    - -threaded
    - -O2
    - -rtsopts
    - -with-rtsopts=-N
